const messages={
 en:{
  experience:'Pixel snow forest under the aurora',scene:'Animated aurora, snow, forest and animals. Click to change the aurora color.',tools:'Controls',
  switchLanguage:'切换到中文',help:'Controls',record:'Record',recordOpen:'Video recording',fullscreen:'Fullscreen',palette:'Aurora',palette0:'Tundra green',palette1:'Twilight violet',palette2:'Crimson',palette3:'Ice blue',
  gestureEnable:'Enable hand',gestureActive:'Hand enabled',gestureCancel:'Cancel loading',surprise:'Forest event',surpriseTitle:'Release snow or summon an animal (W)',pause:'Pause',resume:'Resume',hide:'Hide controls',show:'Show controls',
  hint:'Click to change color · Show or move a hand for an event',reduced:'Animation paused · Press play to walk',
  debug:'Debug',debugToggle:'Hand tracking debug (D)',debugClose:'Close debug window',camera:'Local camera input',cameraOff:'Enable hand tracking to see the camera input.',cameraStop:'Turn off camera',
  debugStatus:'Model',debugHands:'Hands',debugConfidence:'Confidence',debugFPS:'Inference',debugInput:'Input',debugCooldown:'Cooldown',debugEvents:'Events',debugLast:'Last event',
  off:'Off',permission:'Waiting for camera permission',loading:'Loading ml5 HandPose…',ready:'Ready · Show your hand',noHand:'Ready · No hand detected',lowConfidence:'Hand detected · Low confidence',handSeen:'Hand detected · Move slightly for another event',handTrigger:'Hand detected · Event triggered',cooldown:'Hand detected · Cooling down',error:'Error',none:'None',
  close:'Close',helpTitle:'Controls',helpColor:'Click the scene / C',helpColorDetail:'Cycle green, violet, crimson and ice blue.',helpHand:'Show or move your hand / W',helpHandDetail:'After enabling the camera, hold a hand in view briefly or move it a little to trigger a random forest event.',helpDebug:'D',helpDebugDetail:'Toggle camera input, hand landmarks and detection stats. This does not turn on the camera.',helpPause:'Space',helpPauseDetail:'Pause or resume the scene.',helpHide:'H',helpHideDetail:'Hide or restore the controls.',privacy:'Hand tracking loads an ml5 model online on first use. Camera frames stay in your browser. The Forest event button also works without a camera.',
  recordTitle:'Record video',recordDescription:'Only the animation is recorded. Controls and camera input are excluded.',recordSize:'Resolution',recordDuration:'Duration',landscape:'Landscape',portrait:'Portrait',teaser:'15 seconds · teaser',seconds30:'30 seconds',seconds60:'60 seconds',manual:'Manual stop (maximum 3 minutes)',recordStart:'Start recording',recordStop:'Stop recording',recordSupport:'30 fps · {format} · Downloads when finished',recordUnsupported:'Recording requires a recent Chrome, Edge or Safari browser.',recordBusy:'Recording in progress. Use Stop recording to save it.',recordSaved:'Video saved',
  snow:'Snow released',animal:'An animal appeared',noFullscreen:'Fullscreen is unavailable. Use Hide controls instead.',
  libraryTimeout:'ml5 timed out. Check your connection and retry, or use Forest event.',libraryError:'ml5 failed to load. Check your connection and retry, or use Forest event.',libraryInit:'Hand tracking could not initialize.',secureCamera:'Hand tracking needs HTTPS or localhost. Forest event still works.',cameraTimeout:'Camera permission timed out. Allow access and retry.',modelTimeout:'The hand model timed out. Check your connection and retry.',cameraDenied:'Camera access was denied. Allow access and retry, or use Forest event.',cameraMissing:'No camera found. Use Forest event.',cameraBusy:'Camera is in use. Close other camera apps and retry.',gestureFailed:'Hand tracking could not start. Please retry.',inferenceFailed:'Hand tracking stopped. Enable it again, or use Forest event.',recordAlready:'A recording is already in progress.',recordDimensions:'Dimensions must be 320–3840 pixels, with at most 4K total pixels.',recordOptions:'Use 1–60 fps and a duration of 0–180 seconds.',encodingError:'Video encoding failed.'
 },
 zh:{
  experience:'极光下的像素雪地森林',scene:'动态极光、雪地、森林和小动物。点击画面切换极光颜色。',tools:'画面工具',switchLanguage:'Switch to English',help:'操作说明',record:'录制',recordOpen:'视频录制',fullscreen:'全屏',palette:'极光',palette0:'苔原绿',palette1:'暮光紫',palette2:'绯红',palette3:'冰川蓝',
  gestureEnable:'开启手势',gestureActive:'手势已开启',gestureCancel:'取消加载',surprise:'森林事件',surpriseTitle:'随机让树落雪或召唤动物（W）',pause:'暂停',resume:'继续',hide:'隐藏操作',show:'显示操作',hint:'点击画面换色 · 伸手或轻轻移动手触发事件',reduced:'动画已暂停 · 点击播放开始漫步',
  debug:'调试',debugToggle:'手势识别调试（D）',debugClose:'关闭调试窗口',camera:'本地摄像头画面',cameraOff:'开启手势后，这里会显示摄像头输入。',cameraStop:'关闭摄像头',
  debugStatus:'模型状态',debugHands:'检测到的手',debugConfidence:'置信度',debugFPS:'识别帧率',debugInput:'输入尺寸',debugCooldown:'冷却时间',debugEvents:'触发次数',debugLast:'最近事件',
  off:'未开启',permission:'等待摄像头授权',loading:'正在加载 ml5 HandPose…',ready:'模型就绪 · 请伸手',noHand:'模型就绪 · 未检测到手',lowConfidence:'检测到手 · 置信度较低',handSeen:'已检测到手 · 轻轻移动可再次触发',handTrigger:'已检测到手 · 事件已触发',cooldown:'已检测到手 · 冷却中',error:'识别出错',none:'无',
  close:'关闭',helpTitle:'操作说明',helpColor:'点击画面 / C',helpColorDetail:'切换绿色、紫色、绯红和冰蓝极光。',helpHand:'伸手或轻轻移动手 / W',helpHandDetail:'开启摄像头后，将手短暂停留在画面中，或小幅移动，即可随机触发森林事件。',helpDebug:'D',helpDebugDetail:'显示或隐藏摄像头输入、手部关键点和识别数据；不会自动打开摄像头。',helpPause:'空格',helpPauseDetail:'暂停或继续动画。',helpHide:'H',helpHideDetail:'隐藏或恢复操作界面。',privacy:'手势首次使用需要联网加载 ml5 模型。摄像头画面仅在浏览器内用于识别；也可直接点击「森林事件」。',
  recordTitle:'视频录制',recordDescription:'只录制动画画面，不包含操作界面和摄像头。',recordSize:'画面尺寸',recordDuration:'时长',landscape:'横屏',portrait:'竖屏',teaser:'15 秒 · teaser',seconds30:'30 秒',seconds60:'60 秒',manual:'手动结束（最长 3 分钟）',recordStart:'开始录制',recordStop:'结束录制',recordSupport:'30 fps · {format} · 录完自动下载',recordUnsupported:'录制需要新版 Chrome、Edge 或 Safari。',recordBusy:'录制正在进行，点击「结束录制」保存。',recordSaved:'视频已保存',
  snow:'树上的雪落下来了',animal:'小动物出现了',noFullscreen:'当前浏览器不支持全屏，可以隐藏操作界面。',
  libraryTimeout:'ml5 加载超时，请检查网络后重试，也可点击「森林事件」。',libraryError:'ml5 加载失败，请检查网络后重试，也可点击「森林事件」。',libraryInit:'手势库未能初始化。',secureCamera:'手势需要 HTTPS 或 localhost，仍可点击「森林事件」。',cameraTimeout:'摄像头授权等待超时，请允许访问后重试。',modelTimeout:'手势模型加载超时，请检查网络后重试。',cameraDenied:'摄像头未获授权，请允许访问后重试，也可点击「森林事件」。',cameraMissing:'未找到摄像头，可以点击「森林事件」。',cameraBusy:'摄像头正被占用，请关闭其他摄像头应用后重试。',gestureFailed:'手势未能开启，请重试。',inferenceFailed:'手势识别已中断，请重新开启，也可点击「森林事件」。',recordAlready:'已有录制正在进行。',recordDimensions:'录制尺寸应为 320–3840 像素，总像素不超过 4K。',recordOptions:'帧率应为 1–60 fps，时长应为 0–180 秒。',encodingError:'视频编码失败。'
 }
};
export let language='en';
export function t(key,values={}){let message=messages[language][key]??messages.en[key]??key;for(const [k,v]of Object.entries(values))message=message.replaceAll(`{${k}}`,String(v));return message;}
export function setLanguage(next){language=next==='zh'?'zh':'en';if(typeof document==='undefined')return;
 document.documentElement.lang=language==='zh'?'zh-CN':'en';
 for(const el of document.querySelectorAll('[data-i18n]'))el.textContent=t(el.dataset.i18n);
 for(const [data,attr]of [['i18nAria','aria-label'],['i18nTitle','title']])for(const el of document.querySelectorAll(`[data-${data.replace(/[A-Z]/g,m=>'-'+m.toLowerCase())}]`))el.setAttribute(attr,t(el.dataset[data]));
 const button=document.querySelector('#language-button');if(button){button.textContent=language==='en'?'中文':'EN';button.setAttribute('aria-label',t('switchLanguage'));}
 document.dispatchEvent(new Event('languagechange'));
}
