import {createRequire} from 'node:module';
import {writeFile} from 'node:fs/promises';
import assert from 'node:assert/strict';
const require=createRequire(import.meta.url);
const {chromium}=require(process.env.AURORA_NODE_MODULES?`${process.env.AURORA_NODE_MODULES}/playwright`:'playwright');
const browser=await chromium.launch({headless:true,executablePath:process.env.AURORA_CHROME_PATH||undefined,args:['--use-fake-ui-for-media-stream','--use-fake-device-for-media-stream']});
const page=await browser.newPage({viewport:{width:1440,height:900}}),errors=[];
page.on('pageerror',e=>errors.push(e.message));
await page.goto('http://127.0.0.1:8091');await page.waitForFunction(()=>window.auroraWalk?.state.time>.25);
await page.screenshot({path:'media/preview-desktop.png'});
console.log('Desktop loaded',await page.evaluate(()=>window.auroraWalk.state));
await page.locator('[data-palette="1"]').click();assert.equal(await page.evaluate(()=>window.auroraWalk.state.palette),1);
await page.locator('#scene').click({position:{x:600,y:260}});assert.equal(await page.evaluate(()=>window.auroraWalk.state.palette),2);
await page.locator('#pause-button').click();const frozen=await page.evaluate(()=>window.auroraWalk.state.time);await page.waitForTimeout(250);assert.equal(await page.evaluate(()=>window.auroraWalk.state.time),frozen);await page.locator('#pause-button').click();
const events=await page.evaluate(()=>{auroraWalk.triggerEvent('snow');const snow=auroraWalk.state;auroraWalk.triggerEvent('animal');return {snow,after:auroraWalk.state};});assert(events.snow.snowParticles>0);assert(events.after.eventCount>=2);
await page.keyboard.press('h');assert(await page.locator('#experience').evaluate(el=>el.classList.contains('immersive')));await page.keyboard.press('h');
await page.locator('#help-button').click();assert(await page.locator('#help-dialog').evaluate(el=>el.open));await page.keyboard.press('Escape');
await page.locator('#record-button').click();assert(await page.locator('#record-dialog').evaluate(el=>el.open));await page.keyboard.press('Escape');
const recorded=await page.evaluate(async()=>{await auroraWalk.recording.start({width:640,height:360,fps:30,duration:1.2,download:false});return await new Promise(resolve=>setTimeout(async()=>{const r=await auroraWalk.recording.stop();const bytes=new Uint8Array(await r.blob.arrayBuffer());resolve({size:r.blob.size,mime:r.blob.type,duration:r.duration,bytes:Array.from(bytes)});},1600));});
assert(recorded.size>3000);await writeFile(`media/verification-clip.${recorded.mime.includes('mp4')?'mp4':'webm'}`,Buffer.from(recorded.bytes));console.log('Recording verified',recorded.size,recorded.mime,recorded.duration);
await page.setViewportSize({width:390,height:844});await page.waitForTimeout(250);await page.screenshot({path:'media/preview-mobile.png'});assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth),390);
const controls=await page.locator('.controls').boundingBox();assert(controls.x>=0&&controls.x+controls.width<=390);console.log('Mobile controls fit',controls);
await page.setViewportSize({width:1440,height:900});await page.locator('[data-palette="0"]').click();await page.waitForTimeout(750);await page.screenshot({path:'media/preview-desktop.png'});
assert.deepEqual(errors,[]);console.log('No runtime errors.');await browser.close();
